language: python

cache: pip

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages:
      - libstdc++6
      - libfuzzy-dev

python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"

install:
    - bash travis/install_travis.sh

script:
    - bash travis/test_travis.sh
    - mypy tests/testlive_comprehensive.py tests/test_mispevent.py tests/testlive_sync.py pymisp

after_success:
    - pipenv run codecov
    - pipenv run coveralls
