language: python

cache: pip

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages:
      - libstdc++6
      - libfuzzy-dev


matrix:
    include:
        - name: "Python 3.6"
          python: 3.6
          dist: xenial
        - name: "Python 3.6 - Dev"
          python: 3.6-dev
          dist: xenial
        - name: "Python 3.7"
          python: 3.7
          dist: xenial
        - name: "Python 3.7 - Dev"
          python: 3.7-dev
          dist: xenial

install:
    - bash travis/install_travis.sh

script:
    - bash travis/test_travis.sh

after_success:
    - pipenv run codecov
    - pipenv run coveralls
